### PR TITLE
Applied Known Memory Managment Improvements For Marshmallow

### PR DESCRIPTION
**Pull request by SoundsSerious**
Hi @kashifpk 

I've applied several improvements for memory management. #https://github.com/threatify/arango-orm/issues/105

Perhaps we had upgrade the marshmallow `default` change as well, as discussed in #https://github.com/threatify/arango-orm/issues/103

These come in two parts:
1) cleaning up fields & data structures
2) limiting the dynamic creation of marshmallow types, now with dynamic class-based caching

### CODE REVIEW

**Comment by SoundsSerious** [comment]
@kashifpk any word on getting this implemented?

**Review by kashifpk — APPROVED** [review]

**Comment by kashifpk** [comment]
Thanks @SoundsSerious - Merged with master. I'll try to push a release to pypi soon.

**Comment by kashifpk** [comment]
@SoundsSerious - Thank you for your contributions to the project.

@SoundsSerious - There seems to be a problem with the code [here](https://github.com/threatify/arango-orm/blob/master/arango_orm/collections.py#L90).

It seems you added a boolean condition to a for loop iterable. 

image

This is causing tests to fail. 

image

**Comment by SoundsSerious** [comment]
Hmm Yea it looks like this is a problem. Rookie mistake to create a PR and not test the code. Sorry for the headache!

I've just fixed the issues and got the tests working (except for any that requires DB access.. not sure how to do that) . I will create a new PR for your consideration.

**Comment by kashifpk** [comment]
Thanks. For test cases requiring DB access I usually create a database named `test` with username and password also set as `test`

**Pull request merged**
