### PR TITLE
Fixed Several Test Errors

### PR DESCRIPTION
**Pull request by SoundsSerious**
>Simplifying Reference Deletion in __del__
>Fixed Marshmallow Set Hashing with only
>fixed boolean check in for statement (wow this is bad)

### CODE REVIEW

**Comment by SoundsSerious** [comment]
This tests ok on my system except for tests which require DB access.

**Review by kashifpk — APPROVED** [review]

**Comment by kashifpk** [comment]
image

**Comment by kashifpk** [comment]
I'll look into this one and fix.

**Comment by SoundsSerious** [comment]
@kashifpk 

Oh no more issues!

This might work:
```
        for parm,field in self._fields.items(): #Clear Fields
            if hasattr(field,'parent'): field.parent = None
            if hasattr(field,'root'): field.root  = None
            ```

**Comment by SoundsSerious** [comment]
@kashifpk 

Thanks for the headsup on the db test credentials, I was able to verify the hasattr checks work via testing.

```
(smxenv) olly@deathray:~/dropbox/Projects/SMART_X/libs/arango-orm$ python -m unittest discover
/home/olly/miniconda3/envs/smxenv/lib/python3.8/site-packages/marshmallow/fields.py:438: RemovedInMarshmallow4Warning: The 'default' attribute of fields is deprecated. Use 'dump_default' instead.
  warnings.warn(
...{'name': 'test', '_key': '12312', 'dob': '2016-09-12', 'favorite_hobby': None, 'hobby': None, 'age': None, 'is_staff': False}
.{'name': 'test', '_key': '12312', 'dob': None, 'favorite_hobby': None, 'hobby': None, 'age': None, 'is_staff': False}
....dict_keys(['_key', '_timestamp', 'stats', 'host', 'status', 'error_message'])
.../home/olly/miniconda3/envs/smxenv/lib/python3.8/site-packages/marshmallow/fields.py:181: RemovedInMarshmallow4Warning: The 'missing' argument to fields is deprecated. Use 'load_default' instead.
  warnings.warn(
........{'name': 'temp', '_key': '73', 'dob': '2016-09-12', 'favorite_hobby': None, 'hobby': None, 'age': None, 'is_staff': False}
....Error creating collection students, it probably already exists
...  - dropping edge no longer present in graph definition. Please drop the edge and vertex collections manually if you no longer need them:
{'edge_collection': 'dummy_relation', 'from_vertex_collections': ['dummy_from_col_1', 'dummy_from_col_2'], 'to_vertex_collections': ['dummy_to_col_1', 'dummy_to_col_2']}
..Error creating collection students, it probably already exists
Error creating collection subjects, it probably already exists
Error creating collection teachers, it probably already exists
Error creating collection areas, it probably already exists
Error creating collection dummy_from_col_1, it probably already exists
Error creating collection dummy_from_col_2, it probably already exists
Error creating collection dummy_to_col_1, it probably already exists
Error creating collection dummy_to_col_2, it probably already exists
Error creating edge collection studies, it probably already exists
Error creating edge collection teaches, it probably already exists
Error creating edge collection specializes_in, it probably already exists
Error creating edge collection resides_in, it probably already exists
Error creating edge collection dummy_relation, it probably already exists
..........Wonder has got in sleep~
.James has got in sleep~
.Wonder has got in sleep~
..................................
----------------------------------------------------------------------
Ran 74 tests in 0.431s

OK
```

**Comment by kashifpk** [comment]
Nice work @SoundsSerious - Did you push these fixes too? I don't see any new commits.

**Comment by SoundsSerious** [comment]
@SoundsSerious Yes there should be a new PR I just opened for this, hopefully this will be the last of it :)

**Comment by kashifpk** [comment]
The tests pass but the error is still there

image

This is a bit odd, I'll try to look into it. May be `root` is `@property` with no setter.

**Comment by SoundsSerious** [comment]
Hmm i wonder if this has to do with the marshmallow version. I am on `marshmallow    3.15.0`

**Comment by SoundsSerious** [comment]
OK did some scanning of the marshmallow libs:

In `3.15.0` its a regular variable:
https://github.com/marshmallow-code/marshmallow/blob/3.15.0/src/marshmallow/fields.py

In version `3.2.0` its a property!
```
    @property
    def root(self):
        """Reference to the `Schema` that this field belongs to even if it is buried in a
        container field (e.g. `List`).
        Return `None` for unbound fields.
        """
        ret = self
        while hasattr(ret, "parent"):
            ret = ret.parent
        return ret if isinstance(ret, SchemaABC) else None
```

**Comment by SoundsSerious** [comment]
We've discussed issues with marshmallow in the past, #103 

https://github.com/marshmallow-code/marshmallow/issues/1943

I think a solution could be to specify a marshmallow version greater than `3.12.2` although this presents issues with the new warnings

**Comment by kashifpk** [comment]
Yes, I'm on version `3.7.0` so fixing the version seems like the quickest fix. I've fixed the versions and deployed `arango-orm 0.7.0` to pypi. Thanks @SoundsSerious for your hard work.

**Comment by SoundsSerious** [comment]
@kashifpk awesome!! 

Glad to help out! Thanks to you for putting together this library, hopefully more and more people find use in it with arango's growth :)

**Pull request merged**
