### PR TITLE
Bound db to model object

### PR DESCRIPTION
**Pull request by wonderbeyond**
Inspired by http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#how-can-i-get-the-session-for-a-certain-object

An object can be aware of the session, So we can execute related db querys in its method.

---

@kashifpk BTW. can you give a script for initialize the data for running your test cases.

### CODE REVIEW

**Comment by kashifpk** [comment]
@wonderbeyond Thanks for the PR. Can you explain what data initialization script are you referring to? There is https://github.com/threatify/arango-orm/blob/master/tests/data.py that contains data used by the test cases but it doesn't really require initialization as can be seen in https://github.com/threatify/arango-orm/blob/master/tests/test_graph.py

**Comment by wonderbeyond** [comment]
```
$ python test_code.py
Traceback (most recent call last):
  File "test_code.py", line 22, in <module>
    uni_graph.expand(amanda, depth=3)
  File "/home/wonder/workspace/arango-orm/arango_orm/graph.py", line 183, in expand
    doc_id = doc_obj._id
AttributeError: 'NoneType' object has no attribute '_id'
```

So I guessed I miss some of inital data.

**Comment by kashifpk** [comment]
Oh I meant the test cases in the tests folder. Something like:

```shell
arango-orm $ nosetests tests
........................................
----------------------------------------------------------------------
Ran 40 tests in 1.352s

OK

```

The test_code.py was just an early code sample to test out various aspects. It's no longer used.

**Comment by wonderbeyond** [comment]
Many thanks!

**Pull request merged**
