### PR TITLE
using Metaclass for recording schema fields, with other minor fixes

### PR DESCRIPTION
**Pull request by wonderbeyond**
- CollectionMeta for recording schema fields at class declaration setp
- resolves https://github.com/threatify/arango-orm/issues/21
- tested the changes under py27, py34, py35, py36, pypy using tox

---

using tox to run test suite:

```
pip install tox
tox
```

### CODE REVIEW

**Comment by kashifpk** [comment]
@wonderbeyond  - Thank you for the PR, I'm in the middle of writing test cases for #19  and #20, will merge after that so those tests cases also get covered.

**Comment by wonderbeyond** [comment]
wait! the tests is not passed with your latest commits. I'm fixing...

**Comment by wonderbeyond** [comment]
Ready now!

> $ tox
> py27: commands succeeded
> py34: commands succeeded
> py35: commands succeeded
> py36: commands succeeded
> pypy: commands succeeded
> congratulations :)

**Comment by kashifpk** [comment]
@wonderbeyond  - Thanks. Merged your pull requests and updated tests to cover the new functionality I added. They pass without any issues :-)

**Pull request merged**
