### PR TITLE
A very basic event implementation

### PR DESCRIPTION
**Pull request by wonderbeyond**
Resolves https://github.com/threatify/arango-orm/issues/30

### CODE REVIEW

**Comment by kashifpk** [comment]
@wonderbeyond 

Thank you :-)

**Comment by wonderbeyond** [comment]
@kashifpk My pleasure.

Should we add some description for this feature in readme?

**Comment by kashifpk** [comment]
Yes I was thinking the same thing :-) If you want you can update the readme

**Comment by wonderbeyond** [comment]
OK, I may have time tomorrow.
(Bear my pool English)

**Pull request merged**
